# Generated by Django 3.0.1 on 2020-02-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_owner', models.CharField(max_length=60)),
                ('Room_phnumber', models.CharField(max_length=10)),
                ('Room_location', models.CharField(max_length=200)),
                ('Room_price', models.CharField(max_length=10)),
                ('pub_date', models.DateField()),
                ('Room_desc', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
    ]
