# Generated by Django 3.0.1 on 2020-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
