# Generated by Django 3.0.1 on 2020-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200207_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_phnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateField(default=14.020833333333334),
        ),
    ]
