# Generated by Django 3.0.1 on 2020-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200207_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_price',
            field=models.DecimalField(decimal_places=2, default=4000.0, max_digits=7),
        ),
    ]
