# Generated by Django 3.0.1 on 2020-02-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20200205_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Room_ID',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Room_ID',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Buyer_ID',
            new_name='user',
        ),
    ]
