# Generated by Django 3.0.1 on 2020-02-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=10)),
                ('Gender', models.CharField(default='Others', max_length=25)),
                ('Phone_number', models.CharField(max_length=10)),
                ('E_mail', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=10)),
                ('Gender', models.CharField(default='Others', max_length=25)),
                ('Phone_number', models.CharField(max_length=10)),
                ('E_mail', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
